name: Publish resume
on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
    build:
        name: Build preview PDF
        runs-on: ubuntu-latest
        steps:
        - name: Checkout master
          uses: actions/checkout@v3
          with:  
            fetch-depth: 0
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - name: Install typst
          run: 'cargo install --git https://github.com/typst/typst'
        - name: Build PDF
          run: 'typst compile --font-path ./fonts resume.typ 杨翼飞_个人简历.pdf'
        - name: Update Profile
          run: |
            gh repo clone NorthSecond/Profile
            cp -f 杨翼飞_个人简历.pdf ./Profile/assets/pdf/
            cd ./Profile
            git config --global user.email yangyf83@aliyun.com
            git config --global user.name yangyf83
            git add .
            git commit -m "update profile pdf with Github CI/CD"
            gh repo sync
          env:
            GH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
